version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rocky
  - source: /script/aws/httpd-staging2.conf
    destination: /etc/httpd/conf
permissions:
  - object: /var/www/rocky
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type: 
      - directory
  - object: /var/www/rocky
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type: 
      - file
hooks:
  BeforeInstall:
    - location: script/aws/install_lib_dependencies.sh
      timeout: 300
      runas: root
    - location: script/aws/install_rvm_passenger.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: script/aws/rails_setup.sh
      timeout: 300
      runas: ec2-user