module AbrStateMethods::IL
  
  PDF_FIELDS = {'abr_email': {:method=>"email"},
                'abr_first_name': {:method=>"first_name"},
                'abr_last_name': {:method=>"last_name"},
                'abr_street_number': {method: "street_number"},
                'abr_street_name': {method: "street_name"},
                'abr_unit': {:method=>"unit"},
                'abr_city': {:method=>"city"},
                'abr_home_state_abbrev': {:method=>"home_state_abbrev"},
                'abr_zip': {:method=>"zip"},
                'abr_phone': { method: "phone"},
                
                'abr_county': {},
                'abr_precinct': {},

                'abr_mailing_street_number': {},
                'abr_mailing_street_name': {},
                'abr_mailing_unit': {},
                'abr_mailing_city': {},
                'abr_mailing_state_abbrev': {},
                'abr_mailing_zip': {},
                'abr_date_of_birth_mm_dd_yyyy': {
                  method: "date_of_birth_mm_dd_yyyy"
                },

                'abr_election_type1': { value: "Primary" },
                'abr_election_date': { value: "06/28/2022" },

                'abr_party': {},
                'abr_want_nonpartisan_ballot': { options: ["Off", "Yes"]}
  }

  EXTRA_FIELDS = ["has_mailing_address"]
  
  def form_field_items
    [
      {"abr_county": {type: :select, required: true, include_blank: true, options: [
        "Adams",
        "Alexander",
        "Bond",
        "Boone",
        "Brown",
        "Bureau",
        "Calhoun",
        "Carroll",
        "Cass",
        "Champaign",
        "Christian",
        "Clark",
        "Clay",
        "Clinton",
        "Coles",
        "Cook",
        "Crawford",
        "Cumberland",
        "DeKalb",
        "De Witt",
        "Douglas",
        "DuPage",
        "Edgar",
        "Edwards",
        "Effingham",
        "Fayette",
        "Ford",
        "Franklin",
        "Fulton",
        "Gallatin",
        "Greene",
        "Grundy",
        "Hamilton",
        "Hancock",
        "Hardin",
        "Henderson",
        "Henry",
        "Iroquois",
        "Jackson",
        "Jasper",
        "Jefferson",
        "Jersey",
        "Jo Daviess",
        "Johnson",
        "Kane",
        "Kankakee",
        "Kendall",
        "Knox",
        "La Salle",
        "Lake",
        "Lawrence",
        "Lee",
        "Livingston",
        "Logan",
        "McDonough",
        "McHenry",
        "McLean",
        "Macon",
        "Macoupin",
        "Madison",
        "Marion",
        "Marshall",
        "Mason",
        "Massac",
        "Menard",
        "Mercer",
        "Monroe",
        "Montgomery",
        "Morgan",
        "Moultrie",
        "Ogle",
        "Peoria",
        "Perry",
        "Piatt",
        "Pike",
        "Pope",
        "Pulaski",
        "Putnam",
        "Randolph",
        "Richland",
        "Rock Island",
        "Saline",
        "Sangamon",
        "Schuyler",
        "Scott",
        "Shelby",
        "St. Clair",
        "Stark",
        "Stephenson",
        "Tazewell",
        "Union",
        "Vermilion",
        "Wabash",
        "Warren",
        "Washington",
        "Wayne",
        "White",
        "Whiteside",
        "Will",
        "Williamson",
        "Winnebago",
        "Woodford",
      ]}},
      {'abr_precinct': {required: false}},
      {'has_mailing_address': {type: :checkbox}},
      {'abr_mailing_street_number': {required: :if_visible, visible: "has_mailing_address", classes: "quarter"}},
      {'abr_mailing_street_name': {required: :if_visible, visible: "has_mailing_address", classes: "half"}},
      {'abr_mailing_unit': {visible: "has_mailing_address", classes: "quarter"}},
      {'abr_mailing_city': {required: :if_visible, visible: "has_mailing_address", classes: "half"}},
      {'abr_mailing_state_abbrev': {type: :select, required: :if_visible, visible: "has_mailing_address", classes: "quarter", options: GeoState.collection_for_select}},
      {'abr_mailing_zip': {required: :if_visible, visible: "has_mailing_address", classes: "quarter"}},
      {'abr_party_instructions': {type: :instructions}},
      {'abr_party': {required: :if_visible, hidden: "abr_want_nonpartisan_ballot"}},
      {'abr_want_nonpartisan_ballot': { type: :checkbox}},
      
    ]
  end
   
  def full_name_if_has_mailing_address 
    has_mailing_address == "1" ? full_name : ""
  end
   
  def custom_form_field_validations
    # make sure delivery is selected if reason ==3
    # make sure fax is provided if faxtype is selected for delivery
  end
  
 
end
