#!/bin/bash
. /home/ec2-user/.bash_profile    
CURRENT_DIR=/var/www/rocky
#RVM_ENV_DIR=/usr/local/rvm/environments
#RUBY_VERSION=`cat $CURRENT_DIR/.ruby-version`
#GEMSET=`cat $CURRENT_DIR/.ruby-gemset`
ENV_NAME=$1
#source $RVM_ENV_DIR/$RUBY_VERSION@$GEMSET && 
cd $CURRENT_DIR && /usr/local/bin/bundle exec rake -s utility:deactivate_stale_partners RAILS_ENV=$ENV_NAME