#!/bin/bash
CURRENT_DIR=/var/www/rocky
RVM_ENV_DIR=/usr/local/rvm/environments
RUBY_VERSION=`cat $CURRENT_DIR/.ruby-version`
GEMSET=`cat $CURRENT_DIR/.ruby-gemset`
ENV_NAME=$1
source $RVM_ENV_DIR/$RUBY_VERSION@$GEMSET && cd $CURRENT_DIR && bundle exec rake -s utility:deliver_reminders RAILS_ENV=$ENV_NAME