#!/bin/bash
. /home/ec2-user/.bash_profile    
CURRENT_DIR=/var/www/rocky
#RVM_ENV_DIR=/usr/local/rvm/environments
#RUBY_VERSION=`cat $CURRENT_DIR/.ruby-version`
#GEMSET=`cat $CURRENT_DIR/.ruby-gemset`
ENV_NAME=$1
#source $RVM_ENV_DIR/$RUBY_VERSION@$GEMSET && 
export PATH=$PATH:/usr/local/bin:/usr/local/lib/ruby/gems/2.7.0/bin
cd $CURRENT_DIR && RUBYOPT="-W0" bundle exec rake -s utility:deliver_reminders RAILS_ENV=$ENV_NAME