#!/usr/bin/env ruby
rails_root = File.expand_path(File.join(File.dirname(__FILE__), '../'))
Dir.chdir(rails_root)

require 'dotenv'
Dotenv.load(File.join(rails_root, ".env.#{ENV['RAILS_ENV']}"))

require File.expand_path(File.join(rails_root, 'config/environment'))

Dir.chdir(Rails.root)



loop do
  # this will call the regular pdf gen if no priority pdfs are found
  PriorityPdfGeneration.receive_and_generate
  # PdfGeneration.find_and_generate
end