#!/usr/bin/env ruby
require 'dotenv'
Dotenv.load(File.join(File.dirname(__FILE__), '..', ".env.#{ENV['RAILS_ENV']}"))

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config/environment'))

Dir.chdir(Rails.root)



loop do
  # this will call the regular pdf gen if no priority pdfs are found
  PriorityPdfGeneration.receive_and_generate
  # PdfGeneration.find_and_generate
end