#!/usr/bin/env ruby
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config/environment'))

Dir.chdir(Rails.root)

loop do
  # this will call the regular pdf gen if no priority pdfs are found
  #PriorityPdfGeneration.find_and_generate
  PdfGeneration.find_and_generate
end