#!/usr/bin/env ruby
require 'dotenv'
Dotenv.load(File.join(File.dirname(__FILE__), '..', ".env.#{ENV['RAILS_ENV']}"))

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config/environment'))

Dir.chdir(Rails.root)


INTERVAL = 3

class QueueAnalyzer
  def self.get_count
    (PdfGeneration.count || 0) + (PriorityPdfGeneration.count || 0)
  end
  
  def self.seconds_to_empty
    count = self.get_count
    if count > 0
      delta = self.previous_count - count
      self.previous_count = count
      dequeue_per_second = delta / INTERVAL.to_f
      if dequeue_per_second > 0
        return [count / dequeue_per_second, count] # E.g. 20 items at 4 items/sec is 5 secs to dequeue
      else
        return [-1, count]
      end
    else
      return [-1, count]
    end
  end
end

class CloudWatchPublisher
  def self.send(seconds, count)
    t = Time.now
    Rails.logger.debug "Should dequeue #{count} items in #{seconds} seconds."
    cloudwatch = Aws::CloudWatch::Client.new({
      region: 'us-west-2',
      access_key_id: ENV['SQS_AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['SQS_AWS_SECRET_ACCESS_KEY']
    })
    cloudwatch.put_metric_data({
      namespace: "rocky_#{Rails.env}",
      metric_data: [{
        metric_name: "seconds_to_empty",
        value: seconds,
        timestamp: t,
        unit: "Seconds"
      },
      {
        metric_name: "approximate_count",
        value: count,
        timestamp: t
      }]
    })
  end
end

loop do
  # this will call the regular pdf gen if no priority pdfs are found
  seconds, count = QueueAnalyzer.seconds_to_empty
  CloudWatchPublisher.send seconds, count
  sleep INTERVAL
  # PdfGeneration.find_and_generate
end