pdf_host_name: 'example-pdf.com'
api_host_name: 'http://example-api.com'
default_url_host: "register.example.com"
ui_url_host: example.com
use_https: false
paperclip_options: 
  storage: "fog"
  path: ":rails_root/public/system/:attachment/:id/:style/:filename"
  url: "/system/:attachment/:id/:style/:filename"

  
  
hours_before_first_reminder: 0.0333
hours_between_first_and_second_reminder: 0.0333
pdf_expiration_days: .25

states_with_online_registration:
  - AZ
  - CA
  - CO
  - NV
  - WA
  
enabled_locales:
  - en
  - es
  - ko
  - zh-tw

ovr_states:
  CA:
    languages:
      - en
      - es
      - ko
  NV:
    languages:
      - en
  WA:
    languages:
      - en

blocks_configuration:
  default_turf_id: 123
  default_location_id: 123 
  default_staging_location_id: 123
  shift_length: 1
  url: https://svtesting.blocks.work
  partners:
    123:
      turf_id: 234
      canvasser_id: 345
      location_id: 456
      staging_location_id: 567
    124:
      turf_id: 1234
      canvasser_id: 1345
      location_id: 1456
      staging_location_id: 1567